### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Alaev** [eXtremeXR/APIAuthenticationWithNode#1]
@eXtremeX  Should I fork the repo or can you add me as a contributor to it?
Also, I would suggest refactor the code into branches and not commit. it would be easy for us to push the master and users still can view the video specific branch.

**Comment by eXtremeXR** [comment]
I'll definitely add you as a contributor, so we can keep everything here if you're okay with that :)

I'm not sure if I can refactor this in-place, or should I scratch this repo, create the new one with the same name and create different branches for videos?

**Comment by Alaev** [comment]
@eXtremeXR  Yes, I would say that we can refactor the repo just I will try to check out each comment and make a branch for it.

One repo with specific branches for every video would be best. 
You can even give some tasks or assignments in the video so viewers can practice and try to solve problems while you post the next one.

Master branch should hold all the branches code and features that my other users and this way I can set up Travis, Codecove and other CI & CD tools.

**Comment by eXtremeXR** [comment]
If you can do it, that'd be just perfect! If you can't do it for whatever reason, let me know and I'll create a new repo and do the branches thing from the beginning.

I entirely agree - separate branch per video should be the best approach. I'll also try to use GitHub for every CodeWorkr's project from now on.

Overall great!

**Comment by Alaev** [comment]
@eXtremeXR Done.
each episode has its own branch.
I have added pull request with updated readme file for the master branch.
will start working on testing from branch 3.

Can I close this issue?

**Comment by eXtremeXR** [comment]
Hey, absolutely amazing work! You did some GitHub magic there and now this looks much better! :) 

Yes, feel free to close the issue!

**Comment by Alaev** [comment]
The first issue is closed 🎉
