### ISSUE TITLE
NodeOAuth needs to update the security settings 

### ISSUE THREAD

**Issue by ravikirany711** [eXtremeXR/APIAuthenticationWithNode#15]
when i cloned the repo, installed everything , app is running fine , google authentication is working fine 
but when i click login with facebook , its showing 

NodeOAuth needs to update the security settings  and you wont be able to use it until nodeoauth updates its setttings, please fix this

**Comment by eXtremeXR** [comment]
I think you're using my secrets by mistake (ouch, hehe) - you need to create your own projects in Facebook/Google and use your own credentials. Then you'll be in total control and can fix that issue.
