### ISSUE TITLE
Passport.js File is not imported anywhere

### ISSUE THREAD

**Issue by mrfambo** [eXtremeXR/APIAuthenticationWithNode#18]
Hello, I am having a problem. I watched your youtube series and it was simply awesome. The problem I have is that passport.js file has not been imported anywhere so how did the passport come to know about the strategies?

I am having trouble solving it. Please help me.

**Comment by mrfambo** [comment]
Unknown authentication strategy "jwt"
I get this error when I run your code !!!

**Comment by eXtremeXR** [comment]
Hey @mrfambo, 
We have actually imported it in the following file: 
APIAuthenticationWithNode/server/routes/users.js.

We have the following line there: 
const passportConf = require('../passport');

That line makes sure that the passport config (that we wrote, strategies we used etc) is loaded.

Now, a couple of things:
The variable name of passportConf is totally unnecessary, so you can just do this:
require('../passport');

Also, there's nothing special about routes file, you can do the same in app.js file.
