### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by Alaev** [eXtremeXR/APIAuthenticationWithNode#4]
Ok,

I have setup Travis and it looks like it works, however, there is a small problem as I am not the owner or I do not have the repo right I can't set Travis to work on this repo. I think I need to be a part of the organization in the settings of the repo so I can setup Travis working here as well.

I will try to add MongoDB in memory package for a local test or we can come up with some kind of DB seed before each test. 

also, I think there is an issue with mongoose

```
(node:4392) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
```
You can see the Travis build here on my forked repo: [Link](https://travis-ci.org/Alaev/APIAuthenticationWithNode)

**Comment by eXtremeXR** [comment]
Oh, I'll try to fix that. In the repo settings I only see collaborators.

Either DB seed or we can maybe create a user (or so) before each test group gets started (before() in Mocha for example).

About Mongoose, it's actually a bug with newer mongoose version so don't worry about it, I explained it in the video that I'm about to publish. The deprecationwarning only shows in latest mongoose version.

**Comment by Alaev** [comment]
Cool,
I think dbseed can work fine. some kind of function to run before each test suite.

If you are on pc. you can add Travis to this repo and he will watch the .travis.yml file for us.
https://travis-ci.com/
