### ISSUE TITLE
Merge part 8 to master

### ISSUE THREAD

**Issue by Alaev** [eXtremeXR/APIAuthenticationWithNode#6]
Should we merge part 8 to master?

**Comment by eXtremeXR** [comment]
Hey, I already merged the changes. I just then went to branch #8 again and updated README, so I didn't want to merge again as we want to keep the original README in master.

That should be alright, correct?

I however didn't open pull request, sorry have to get used to it :)

**Comment by Alaev** [comment]
Ohh that cool. I would only change one thing in the commit.
see https://github.com/eXtremeXR/APIAuthenticationWithNode/commit/5a871c1ef6f277e26067650c5d0c60c24974a8c9

**Comment by Alaev** [comment]
closing this question.
